# avatar config
avatars:
  - id: 10
    key: sunny
    name: Sunny
    age: 21
    bio: Live Streamer. Voice/Text mode available.
    photo: /avatar/sunny.jpg
    level: "50,000"
    location: Japan
    tags: ["#Live", "#Cute", "#VoiceMode"]
    intimacy: 25
    next_reward: Special Video
    live: true
    prompt_file: prompt_sunny.txt
    model_avatar_id: wav2lip_avatar1
    model_avatar_id_ex: wav2lip_avatar1_ex
    elevenlabs_voice_id: iZTnOiLNxroAzRmv4oht 
